language: python

python:
  - "2.6"
  - "2.7"

# install system dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev

# install python dependencies
install:
  - pip install numpy numexpr Cython
  - pip install tables
  - pip install pandas h5py MDAnalysis
  - pip install .

# run tests
script: py.test
