language: python
sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev

python:
  - "2.7"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install --upgrade pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython
  - pip install MDAnalysisTests
  - pip install --process-dependency-links -e .

# run tests
script: 
  - py.test --cov src --pep8 src

after_success:
  - codecov
