language: python
sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev

python:
  - "2.7"

# whitelist
branches:
    only:
        - master
        - develop

env:
  matrix:
    - DATREANT_DEV="true"
    - DATREANT_DEV="false"

matrix:
  allow_failures:
    - env: DATREANT_DEV="true"

# install python dependencies
install:
  - pip install codecov
  - pip install --upgrade pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython
  - pip install MDAnalysisTests
  - |
    if [[ $DATREANT_DEV == 'true' ]]; then \
      pip install git+https://github.com/datreant/datreant.core.git;\
    fi
  - pip install --process-dependency-links -e .

# run tests
script: 
  - py.test --cov src --pep8 src

after_success:
  - codecov
