language: python
sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev

python:
  - "2.7"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy numexpr Cython  # keep because PyTables or MDAnalysis fail to install otherwise
  - python setup.py install

# run tests
script: 
  - py.test --cov mdsynthesis --pep8 mdsynthesis

after_success:
  - codecov
