package:
  name: mdsynthesis
  version: "0.6.1"

source:
   # path: .
   git_url: https://github.com/datreant/MDSynthesis
   # git_branch: master
   git_tag: 0.6.1

build:
    noarch_python: True
    script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - datreant.core
    - datreant.data
    - mdanalysis


  run:
    - python
    - datreant.core
    - datreant.data
    - mdanalysis

test:
  # Python imports
  imports:
    - mdsynthesis

  requires:
    # Put any additional test requirements here.  For example
    - pytest
    - datreant.core
    - datreant.data
    - mdanalysis

  files:
   - src/mdsynthesis/tests

  commands:
    - py.test src

about:
  home: http://mdsynthesis.readthedocs.io/en/master/
  license: GPLVv2
  license_file: LICENSE.txt
  summary: 'a persistence engine for molecular dynamics data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
